name: "SonarCloud Analysis for Flutter"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      - name: Find Flutter Project
        id: find_flutter
        run: |
          if [ -f "pubspec.yaml" ]; then
            echo "PROJECT_DIR=." >> $GITHUB_ENV
          elif [ -f "flutter_app/pubspec.yaml" ]; then
            echo "PROJECT_DIR=flutter_app" >> $GITHUB_ENV
          else
            echo "Error: Cannot find pubspec.yaml!" >&2
            exit 1
          fi

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Flutter Analyze
        run: flutter analyze
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Flutter Build
        run: flutter build apk --debug
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Run SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ${{ env.PROJECT_DIR }}
          extraProperties: |
            sonar.projectKey=YOUR_PROJECT_KEY
            sonar.organization=YOUR_ORG_KEY
            sonar.sources=lib
            sonar.exclusions=**/build/**, **/*.g.dart
            sonar.c.file.suffixes=-
            sonar.cpp.file.suffixes=-
            sonar.objc.file.suffixes=-
